// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_user_languages.sql

package database

import (
	"context"
	"database/sql"
)

const createAgentUserLanguage = `-- name: CreateAgentUserLanguage :exec
INSERT INTO agent_user_languages (agent_id, language_id)
VALUES (
    ?,
    ?
)
`

type CreateAgentUserLanguageParams struct {
	AgentID    sql.NullString
	LanguageID sql.NullInt64
}

func (q *Queries) CreateAgentUserLanguage(ctx context.Context, arg CreateAgentUserLanguageParams) error {
	_, err := q.db.ExecContext(ctx, createAgentUserLanguage, arg.AgentID, arg.LanguageID)
	return err
}
