// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_specializations.sql

package database

import (
	"context"
	"database/sql"
)

const createAgentSpecialization = `-- name: CreateAgentSpecialization :exec
INSERT INTO agent_specializations (agent_id, specialization_id)
VALUES (
    ?,
    ?
)
ON CONFLICT(agent_id, specialization_id) DO NOTHING
`

type CreateAgentSpecializationParams struct {
	AgentID          sql.NullString
	SpecializationID sql.NullInt64
}

func (q *Queries) CreateAgentSpecialization(ctx context.Context, arg CreateAgentSpecializationParams) error {
	_, err := q.db.ExecContext(ctx, createAgentSpecialization, arg.AgentID, arg.SpecializationID)
	return err
}
