// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_marketing_areas.sql

package database

import (
	"context"
	"database/sql"
)

const createAgentMarketingArea = `-- name: CreateAgentMarketingArea :exec
INSERT INTO agent_marketing_areas (agent_id, area_id)
VALUES (
    ?,
    ?
)
`

type CreateAgentMarketingAreaParams struct {
	AgentID sql.NullString
	AreaID  sql.NullInt64
}

func (q *Queries) CreateAgentMarketingArea(ctx context.Context, arg CreateAgentMarketingAreaParams) error {
	_, err := q.db.ExecContext(ctx, createAgentMarketingArea, arg.AgentID, arg.AreaID)
	return err
}
