// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_feed_licenses.sql

package database

import (
	"context"
	"database/sql"
)

const createAgentFeedLicense = `-- name: CreateAgentFeedLicense :exec
INSERT INTO agent_feed_licenses (agent_id, feed_license_id)
VALUES (
    ?,
    ?
)
ON CONFLICT(agent_id, feed_license_id) DO NOTHING
`

type CreateAgentFeedLicenseParams struct {
	AgentID       sql.NullString
	FeedLicenseID sql.NullInt64
}

func (q *Queries) CreateAgentFeedLicense(ctx context.Context, arg CreateAgentFeedLicenseParams) error {
	_, err := q.db.ExecContext(ctx, createAgentFeedLicense, arg.AgentID, arg.FeedLicenseID)
	return err
}
