// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent_languages.sql

package database

import (
	"context"
	"database/sql"
)

const createAgentLanguage = `-- name: CreateAgentLanguage :exec
INSERT INTO agent_languages (agent_id, language_id)
VALUES (
    ?,
    ?
)
ON CONFLICT(agent_id, language_id) DO NOTHING
`

type CreateAgentLanguageParams struct {
	AgentID    sql.NullString
	LanguageID sql.NullInt64
}

func (q *Queries) CreateAgentLanguage(ctx context.Context, arg CreateAgentLanguageParams) error {
	_, err := q.db.ExecContext(ctx, createAgentLanguage, arg.AgentID, arg.LanguageID)
	return err
}
