// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: brokers.sql

package database

import (
	"context"
	"database/sql"
)

const createBroker = `-- name: CreateBroker :one
INSERT INTO brokers (fulfillment_id, name, photo, video)
VALUES (
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT(fulfillment_id) DO NOTHING
RETURNING id
`

type CreateBrokerParams struct {
	FulfillmentID sql.NullInt64
	Name          sql.NullString
	Photo         sql.NullString
	Video         sql.NullString
}

func (q *Queries) CreateBroker(ctx context.Context, arg CreateBrokerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBroker,
		arg.FulfillmentID,
		arg.Name,
		arg.Photo,
		arg.Video,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBrokerID = `-- name: GetBrokerID :one
SELECT id FROM brokers
WHERE fulfillment_id = ? 
LIMIT 1
`

func (q *Queries) GetBrokerID(ctx context.Context, fulfillmentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBrokerID, fulfillmentID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
