// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed_licenses.sql

package database

import (
	"context"
	"database/sql"
)

const createFeedLicense = `-- name: CreateFeedLicense :one
INSERT INTO feed_licenses (agent_id, country, state_code, license_number)
VALUES (
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT(agent_id, country, state_code, license_number) 
    DO NOTHING
RETURNING id, country, license_number, state_code, agent_id
`

type CreateFeedLicenseParams struct {
	AgentID       sql.NullString
	Country       sql.NullString
	StateCode     sql.NullString
	LicenseNumber sql.NullString
}

func (q *Queries) CreateFeedLicense(ctx context.Context, arg CreateFeedLicenseParams) (FeedLicense, error) {
	row := q.db.QueryRowContext(ctx, createFeedLicense,
		arg.AgentID,
		arg.Country,
		arg.StateCode,
		arg.LicenseNumber,
	)
	var i FeedLicense
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.LicenseNumber,
		&i.StateCode,
		&i.AgentID,
	)
	return i, err
}
