// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed_licenses.sql

package database

import (
	"context"
	"database/sql"
)

const createFeedLicense = `-- name: CreateFeedLicense :exec
INSERT INTO feed_licenses (agent_id, country, state_code, license_number)
VALUES (
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT(agent_id, country, state_code, license_number) DO NOTHING
`

type CreateFeedLicenseParams struct {
	AgentID       sql.NullString
	Country       sql.NullString
	StateCode     sql.NullString
	LicenseNumber sql.NullString
}

func (q *Queries) CreateFeedLicense(ctx context.Context, arg CreateFeedLicenseParams) error {
	_, err := q.db.ExecContext(ctx, createFeedLicense,
		arg.AgentID,
		arg.Country,
		arg.StateCode,
		arg.LicenseNumber,
	)
	return err
}
