// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: languages.sql

package database

import (
	"context"
	"database/sql"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (name)
VALUES (?)
ON CONFLICT(name) DO NOTHING
RETURNING id, name
`

func (q *Queries) CreateLanguage(ctx context.Context, name sql.NullString) (Language, error) {
	row := q.db.QueryRowContext(ctx, createLanguage, name)
	var i Language
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getLanguage = `-- name: GetLanguage :one
SELECT id, name FROM languages 
WHERE name = ? 
LIMIT 1
`

func (q *Queries) GetLanguage(ctx context.Context, name sql.NullString) (Language, error) {
	row := q.db.QueryRowContext(ctx, getLanguage, name)
	var i Language
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
