// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: listings_data.sql

package database

import (
	"context"
	"database/sql"
)

const createListingsData = `-- name: CreateListingsData :exec
INSERT INTO listings_data (count, min, max, last_listing_date, agent_id)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT (agent_id) 
DO UPDATE SET
    count = EXCLUDED.count,
    min = EXCLUDED.min,
    max = EXCLUDED.max,
    last_listing_date = EXCLUDED.last_listing_date
`

type CreateListingsDataParams struct {
	Count           sql.NullInt64
	Min             sql.NullInt64
	Max             sql.NullInt64
	LastListingDate sql.NullTime
	AgentID         sql.NullString
}

func (q *Queries) CreateListingsData(ctx context.Context, arg CreateListingsDataParams) error {
	_, err := q.db.ExecContext(ctx, createListingsData,
		arg.Count,
		arg.Min,
		arg.Max,
		arg.LastListingDate,
		arg.AgentID,
	)
	return err
}
