// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: multiple_listing_services.sql

package database

import (
	"context"
	"database/sql"
)

const createMultipleListingService = `-- name: CreateMultipleListingService :one
INSERT INTO multiple_listing_services (abbreviation, inactivation_date, license_number, member_id, type, is_primary)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT (abbreviation, license_number, member_id, type)
    DO NOTHING
RETURNING id, abbreviation, inactivation_date, license_number, member_id, type, is_primary
`

type CreateMultipleListingServiceParams struct {
	Abbreviation     sql.NullString
	InactivationDate sql.NullTime
	LicenseNumber    sql.NullString
	MemberID         sql.NullString
	Type             sql.NullString
	IsPrimary        sql.NullBool
}

func (q *Queries) CreateMultipleListingService(ctx context.Context, arg CreateMultipleListingServiceParams) (MultipleListingService, error) {
	row := q.db.QueryRowContext(ctx, createMultipleListingService,
		arg.Abbreviation,
		arg.InactivationDate,
		arg.LicenseNumber,
		arg.MemberID,
		arg.Type,
		arg.IsPrimary,
	)
	var i MultipleListingService
	err := row.Scan(
		&i.ID,
		&i.Abbreviation,
		&i.InactivationDate,
		&i.LicenseNumber,
		&i.MemberID,
		&i.Type,
		&i.IsPrimary,
	)
	return i, err
}

const getMultipleListingService = `-- name: GetMultipleListingService :one
SELECT id, abbreviation, inactivation_date, license_number, member_id, type, is_primary FROM multiple_listing_services
WHERE abbreviation = ? AND type = ? AND member_id = ? AND license_number = ?
LIMIT 1
`

type GetMultipleListingServiceParams struct {
	Abbreviation  sql.NullString
	Type          sql.NullString
	MemberID      sql.NullString
	LicenseNumber sql.NullString
}

func (q *Queries) GetMultipleListingService(ctx context.Context, arg GetMultipleListingServiceParams) (MultipleListingService, error) {
	row := q.db.QueryRowContext(ctx, getMultipleListingService,
		arg.Abbreviation,
		arg.Type,
		arg.MemberID,
		arg.LicenseNumber,
	)
	var i MultipleListingService
	err := row.Scan(
		&i.ID,
		&i.Abbreviation,
		&i.InactivationDate,
		&i.LicenseNumber,
		&i.MemberID,
		&i.Type,
		&i.IsPrimary,
	)
	return i, err
}

const updateMultipleListingServiceInactivationDate = `-- name: UpdateMultipleListingServiceInactivationDate :exec
UPDATE multiple_listing_services
SET inactivation_date = ?
WHERE id = ?
`

type UpdateMultipleListingServiceInactivationDateParams struct {
	InactivationDate sql.NullTime
	ID               int64
}

func (q *Queries) UpdateMultipleListingServiceInactivationDate(ctx context.Context, arg UpdateMultipleListingServiceInactivationDateParams) error {
	_, err := q.db.ExecContext(ctx, updateMultipleListingServiceInactivationDate, arg.InactivationDate, arg.ID)
	return err
}
