// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: multiple_listing_services.sql

package database

import (
	"context"
	"database/sql"
)

const createMultipleListingService = `-- name: CreateMultipleListingService :one
INSERT INTO multiple_listing_services (abbreviation, inactivation_date, license_number, member_id, type, is_primary)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, abbreviation, inactivation_date, license_number, member_id, type, is_primary
`

type CreateMultipleListingServiceParams struct {
	Abbreviation     sql.NullString
	InactivationDate sql.NullTime
	LicenseNumber    sql.NullString
	MemberID         sql.NullString
	Type             sql.NullString
	IsPrimary        sql.NullBool
}

func (q *Queries) CreateMultipleListingService(ctx context.Context, arg CreateMultipleListingServiceParams) (MultipleListingService, error) {
	row := q.db.QueryRowContext(ctx, createMultipleListingService,
		arg.Abbreviation,
		arg.InactivationDate,
		arg.LicenseNumber,
		arg.MemberID,
		arg.Type,
		arg.IsPrimary,
	)
	var i MultipleListingService
	err := row.Scan(
		&i.ID,
		&i.Abbreviation,
		&i.InactivationDate,
		&i.LicenseNumber,
		&i.MemberID,
		&i.Type,
		&i.IsPrimary,
	)
	return i, err
}
