// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: office_feed_licenses.sql

package database

import (
	"context"
	"database/sql"
)

const createOfficeFeedLicense = `-- name: CreateOfficeFeedLicense :exec
INSERT INTO office_feed_licenses (office_id, feed_license_id)
VALUES (
    ?,
    ?
)
ON CONFLICT(office_id, feed_license_id) DO NOTHING
`

type CreateOfficeFeedLicenseParams struct {
	OfficeID      sql.NullInt64
	FeedLicenseID sql.NullInt64
}

func (q *Queries) CreateOfficeFeedLicense(ctx context.Context, arg CreateOfficeFeedLicenseParams) error {
	_, err := q.db.ExecContext(ctx, createOfficeFeedLicense, arg.OfficeID, arg.FeedLicenseID)
	return err
}
