// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: raw_agents.sql

package database

import (
	"context"
	"database/sql"
)

const createRawAgent = `-- name: CreateRawAgent :exec
INSERT INTO raw_agents (data, agent_id)
VALUES (
    ?,
    ?
)
ON CONFLICT (agent_id) 
DO UPDATE SET data = EXCLUDED.data
`

type CreateRawAgentParams struct {
	Data    sql.NullString
	AgentID sql.NullString
}

func (q *Queries) CreateRawAgent(ctx context.Context, arg CreateRawAgentParams) error {
	_, err := q.db.ExecContext(ctx, createRawAgent, arg.Data, arg.AgentID)
	return err
}
