// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sales_data.sql

package database

import (
	"context"
	"database/sql"
)

const createSalesData = `-- name: CreateSalesData :exec
INSERT INTO sales_data (count, min, max, last_sold_date, agent_id)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
ON CONFLICT (agent_id) 
DO UPDATE SET
    count = EXCLUDED.count,
    min = EXCLUDED.min,
    max = EXCLUDED.max,
    last_sold_date = EXCLUDED.last_sold_date
`

type CreateSalesDataParams struct {
	Count        sql.NullInt64
	Min          sql.NullInt64
	Max          sql.NullInt64
	LastSoldDate sql.NullTime
	AgentID      sql.NullString
}

func (q *Queries) CreateSalesData(ctx context.Context, arg CreateSalesDataParams) error {
	_, err := q.db.ExecContext(ctx, createSalesData,
		arg.Count,
		arg.Min,
		arg.Max,
		arg.LastSoldDate,
		arg.AgentID,
	)
	return err
}
