// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: social_medias.sql

package database

import (
	"context"
	"database/sql"
)

const createSocialMedia = `-- name: CreateSocialMedia :exec
INSERT INTO social_medias (type, href, agent_id)
VALUES (
    ?,
    ?,
    ?
)
ON CONFLICT (agent_id, href) DO NOTHING
`

type CreateSocialMediaParams struct {
	Type    sql.NullString
	Href    sql.NullString
	AgentID sql.NullString
}

func (q *Queries) CreateSocialMedia(ctx context.Context, arg CreateSocialMediaParams) error {
	_, err := q.db.ExecContext(ctx, createSocialMedia, arg.Type, arg.Href, arg.AgentID)
	return err
}
