// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: social_medias.sql

package database

import (
	"context"
	"database/sql"
)

const createSocialMedia = `-- name: CreateSocialMedia :one
INSERT INTO social_medias (type, href, agent_id)
VALUES (
    ?,
    ?,
    ?
)
RETURNING id, type, href, agent_id
`

type CreateSocialMediaParams struct {
	Type    sql.NullString
	Href    sql.NullString
	AgentID sql.NullString
}

func (q *Queries) CreateSocialMedia(ctx context.Context, arg CreateSocialMediaParams) (SocialMedia, error) {
	row := q.db.QueryRowContext(ctx, createSocialMedia, arg.Type, arg.Href, arg.AgentID)
	var i SocialMedia
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Href,
		&i.AgentID,
	)
	return i, err
}
