// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: specializations.sql

package database

import (
	"context"
	"database/sql"
)

const createSpecialization = `-- name: CreateSpecialization :one
INSERT INTO specializations (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) CreateSpecialization(ctx context.Context, name sql.NullString) (Specialization, error) {
	row := q.db.QueryRowContext(ctx, createSpecialization, name)
	var i Specialization
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
