// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: zips.sql

package database

import (
	"context"
	"database/sql"
)

const createZip = `-- name: CreateZip :one
INSERT INTO zips (zip_code)
VALUES (?)
ON CONFLICT(zip_code) DO UPDATE SET zip_code = EXCLUDED.zip_code
RETURNING id, zip_code
`

func (q *Queries) CreateZip(ctx context.Context, zipCode sql.NullString) (Zip, error) {
	row := q.db.QueryRowContext(ctx, createZip, zipCode)
	var i Zip
	err := row.Scan(&i.ID, &i.ZipCode)
	return i, err
}
